name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-linux-32bit:
    name: build-linux-32bit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            gcc-5-multilib g++-5-multilib \
            libgl1-mesa-dev:i386 \
            qttools5-dev:i386 \
            libstdc++6:i386 \
            libgcc1:i386 \
            zlib1g:i386

      - name: Build
        run: |
          export JAVA_HOME=$JAVA_HOME_8_X64
          mkdir build
          cd build
          cmake \
           -DCMAKE_C_COMPILER=/usr/bin/gcc-5 \
           -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 \
           -DCMAKE_BUILD_TYPE=Release \
           -DLauncher_NOTIFICATION_URL:STRING=https://files.multimc.org/notifications.json \
           -DCMAKE_INSTALL_PREFIX:PATH=/home/runner/UltimMC/UltimMC \
           -DLauncher_UPDATER_BASE=https://files.multimc.org/update/ \
           -DLauncher_PASTE_EE_API_KEY:STRING=utLvciUouSURFzfjPxLBf5W4ISsUX4pwBDF7N1AfZ \
           -DLauncher_ANALYTICS_ID:STRING=UA-87731965-2 \
           -DLauncher_LAYOUT=lin-nodeps \
           -DLauncher_BUILD_PLATFORM=lin32 \
           -DLauncher_BUG_TRACKER_URL=https://github.com/UltimMC/Launcher/issues \
           -DLauncher_EMBED_SECRETS=On \
           -DCMAKE_C_FLAGS="-m32" \
           -DCMAKE_CXX_FLAGS="-m32" \
           $GITHUB_WORKSPACE

      - name: Compile
        run: |
          cd build
          make -j$(nproc)

      - name: Install
        run: |
          cd build
          make install
          chmod +x /home/runner/UltimMC/UltimMC/UltimMC
          chmod +x /home/runner/UltimMC/UltimMC/bin/UltimMC

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: mmc-cracked-lin32
          path: /home/runner/UltimMC
